---
- hosts: finalproject
  become: yes
  tasks:
          - name: Install PHP on Ubuntu
            apt:
                    name: "{{ item }}"
                    state: present
            loop:
                    - php7.4
                    - php7.4-fpm
            when:
                    ansible_os_family == "Debian"
          - name: Install LAMP stack
            apt:
                    pkg:
                            - php7.4-mysql
                            - php7.4-curl
                            - php7.4-json
                            - php7.4-cgi
                            - php7.4-xsl
                            - php7.4-gd
                            - php7.4-mbstring
                            - php7.4-zip
                            - php7.4-xmlrpc
                            - php7.4-soap
                            - php7.4-intl
                            - libapache2-mod-php7.4
                    state: present
