---
- hosts: all
  become: yes
  tasks:
          - name: Install Elasticsearch on Ubuntu
            apt:
                    deb: https://www.techplanet.pro/d/elasticsearch-7.17.1-amd64.deb
                    state: present
            when:
                    ansible_os_family == "Debian"
            notify:
                    elasticsearch systemd
          - name: Install Logstash on Ubuntu
            apt:
                    deb: https://www.techplanet.pro/d/logstash-7.17.1-amd64.deb
                    state: present
            when:
                    ansible_os_family == "Debian"
            notify:
                    logstash systemd
          - name: Install Kibana on Ubuntu
            apt:
                    deb: https://www.techplanet.pro/d/kibana-7.17.1-amd64.deb
                    state: present
            when: 
                    ansible_os_family == "Debian"
            notify:
                    kibana systemd
  handlers:
          - name: elasticsearch systemd
            systemd:
                    name: elasticsearch.service
                    enabled: yes
                    state: started
          - name: logstash systemd
            systemd:
                    name: logstash.service
                    enabled: yes
                    state: started
          - name: kibana systemd
            systemd:
                    name: kibana.service
                    enabled: yes
                    state: started
