---
- hosts: all
  become: yes
  tasks:
          - name: Install Apache
            apt:
                    name=apache2
                    state=latest
          - name: Enable mod_rewrite
            apache2_module:
                    name=rewrite
                    state=present
          - name: change listen port
            lineinfile:
                    path: /etc/apache2/ports.conf
                    regexp: '^Listen 80'
                    insertbefore: BOF
                    line: 'Listen 8080'
                    backrefs: yes
          - name: change listen SSL port
            lineinfile:
                    path: /etc/apache2/ports.conf
                    insertbefore: BOF
                    firstmatch=yes
                    regexp: '^Listen 443'
                    line: 'Listen 8443'
                    backrefs: yes
            notify:
                    - restart apache2
  handlers:
          - name: restart apache2
            service:
                    name=apache2
                    state=restarted
