---
- hosts: all
  become: yes
  tasks:
          - name: Install Filebeat on Ubuntu
            apt:
                    deb: https://www.techplanet.pro/d/filebeat-7.17.1-amd64.deb
                    state: present
            when:
                    ansible_os_family == "Debian"
            notify:
                    filebeat systemd
  handlers:
          - name: filebeat systemd
            systemd:
                    name: filebeat.service
                    enabled: yes
                    state: started
