---
- hosts: all
  become: yes
  tasks:
          - name: Set Postfix option hostname
            debconf:
                    name=postfix
                    question="postfix/mailname"
                    value="sandbox"
                    vtype="string"
          - name: Set Postfix option type as internet site
            debconf:
                    name=postfix
                    question="postfix/main_mailer_type"
                    value="'Internet Site'"
                    vtype="string"
          - name: Install Postfix
            apt:
                    name=postfix
                    state=present
  handlers:
          - name: restart postfix
            service:
                    name=postfix
                    state=restarted
